const problems = [
  { title:"const로 변수 선언하기", description:'const를 사용하여 school이라는 변수를 선언하고, "대구공업고등학교"를 저장한 후 출력하세요.', conditions:["변수 이름은 school로 작성합니다.","반드시 const를 사용합니다.","console.log()로 변수를 출력합니다."], starter:"", output:"대구공업고등학교", solution:'const school = "대구공업고등학교";\n\nconsole.log(school);', validate:c=>test(c,/const\s+school\s*=\s*(["'])대구공업고등학교\1\s*;?/)&&logs(c,"school") },
  { title:"let으로 변수 선언하기", description:"let을 사용하여 studentCount라는 변수를 선언하고 20을 저장한 후 출력하세요.", conditions:["변수 이름은 studentCount로 작성합니다.","반드시 let을 사용합니다.","숫자를 직접 출력하지 말고 변수를 출력합니다."], starter:"", output:"20", solution:"let studentCount = 20;\n\nconsole.log(studentCount);", validate:c=>test(c,/let\s+studentCount\s*=\s*20\s*;?/)&&logs(c,"studentCount") },
  { title:"변수의 값 변경하기", description:'level 변수에 저장된 값을 "중급"으로 변경한 후 출력하세요.', conditions:["새로운 변수를 만들지 않습니다.","level에 새로운 값을 저장합니다."], starter:'let level = "초급";\n\n// 여기에 코드를 작성하세요.\n\nconsole.log(level);', output:"중급", solution:'let level = "초급";\n\nlevel = "중급";\n\nconsole.log(level);', validate:c=>test(c,/let\s+level\s*=\s*(["'])초급\1\s*;?/)&&test(c,/level\s*=\s*(["'])중급\1\s*;?/)&&logs(c,"level") },
  { title:"마지막에 저장한 값 확인하기", description:'빈칸에 알맞은 코드를 작성하여 마지막에 "완료"가 출력되도록 하세요.', conditions:["status 변수에 새로운 값을 저장합니다.","주어진 출력문은 변경하지 않습니다."], starter:'let status = "준비";\nstatus = "진행 중";\n\n// 여기에 코드를 작성하세요.\n\nconsole.log(status);', output:"완료", solution:'let status = "준비";\nstatus = "진행 중";\nstatus = "완료";\n\nconsole.log(status);', validate:c=>test(c,/status\s*=\s*(["'])완료\1\s*;?/)&&logs(c,"status") },
  { title:"다른 변수의 값 저장하기", description:"originalColor 변수에 저장된 값을 copiedColor 변수에 저장하고, copiedColor를 출력하세요.", conditions:['copiedColor에 "파란색"을 직접 저장하면 안 됩니다.',"반드시 originalColor 변수를 이용합니다.","copiedColor는 const로 선언합니다."], starter:'const originalColor = "파란색";\n\n// copiedColor 변수를 선언하세요.\n\nconsole.log(copiedColor);', output:"파란색", solution:'const originalColor = "파란색";\nconst copiedColor = originalColor;\n\nconsole.log(copiedColor);', validate:c=>test(c,/const\s+copiedColor\s*=\s*originalColor\s*;?/)&&logs(c,"copiedColor") },
  { title:"원본 변수와 복사한 변수 구분하기", description:'secondName에 firstName의 값을 저장하세요. 그다음 firstName의 값을 "이서준"으로 변경하고 두 변수를 차례로 출력하세요.', conditions:["secondName에는 firstName 변수를 이용해 값을 저장합니다.","출력문의 순서를 변경하지 않습니다."], starter:'let firstName = "김민준";\nlet secondName;\n\n// 여기에 코드를 작성하세요.\n\nconsole.log(firstName);\nconsole.log(secondName);', output:"이서준\n김민준", solution:'let firstName = "김민준";\nlet secondName;\n\nsecondName = firstName;\nfirstName = "이서준";\n\nconsole.log(firstName);\nconsole.log(secondName);', validate:c=>test(c,/secondName\s*=\s*firstName\s*;?/)&&test(c,/firstName\s*=\s*(["'])이서준\1\s*;?/)&&logsOrder(c,["firstName","secondName"]) },
  { title:"두 변수의 값 서로 바꾸기", description:"left와 right에 저장된 값을 서로 바꾼 후 출력하세요.", conditions:['"왼쪽"과 "오른쪽"을 다시 직접 입력하면 안 됩니다.',"새로운 변수 temp를 사용합니다.","연산자는 사용하지 않습니다."], starter:'let left = "왼쪽";\nlet right = "오른쪽";\n\n// 여기에 코드를 작성하세요.\n\nconsole.log(left);\nconsole.log(right);', output:"오른쪽\n왼쪽", solution:'let left = "왼쪽";\nlet right = "오른쪽";\n\nlet temp = left;\nleft = right;\nright = temp;\n\nconsole.log(left);\nconsole.log(right);', validate:c=>test(c,/let\s+temp\s*=\s*left\s*;?/)&&test(c,/left\s*=\s*right\s*;?/)&&test(c,/right\s*=\s*temp\s*;?/)&&logsOrder(c,["left","right"]) },
  { title:"const와 let 알맞게 사용하기", description:"변경하지 않을 userName과 값이 변경되는 currentPage를 알맞은 선언 키워드로 작성하세요.", conditions:['userName에는 "홍길동"을 저장하고 변경하지 않습니다.',"currentPage에는 처음 1을 저장한 후 2로 변경합니다.","변경하지 않는 변수는 const, 변경되는 변수는 let으로 선언합니다."], starter:"", output:"홍길동\n2", solution:'const userName = "홍길동";\nlet currentPage = 1;\n\ncurrentPage = 2;\n\nconsole.log(userName);\nconsole.log(currentPage);', validate:c=>test(c,/const\s+userName\s*=\s*(["'])홍길동\1\s*;?/)&&test(c,/let\s+currentPage\s*=\s*1\s*;?/)&&test(c,/currentPage\s*=\s*2\s*;?/)&&logsOrder(c,["userName","currentPage"]) }
];

let current=0;
let studentNumber="----";
const el=id=>document.getElementById(id);
const clean=code=>code.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\/\/.*$/gm,"");
const test=(code,regex)=>regex.test(clean(code));
const logs=(code,name)=>new RegExp(`console\\.log\\(\\s*${name}\\s*\\)\\s*;?`).test(clean(code));
function logsOrder(code,names){let pos=-1;const c=clean(code);return names.every(name=>{const regex=new RegExp(`console\\.log\\(\\s*${name}\\s*\\)\\s*;?`,"g");regex.lastIndex=pos+1;const found=regex.exec(c);if(!found)return false;pos=found.index;return true;});}
function lines(){el("lineNumbers").textContent=Array.from({length:el("codeInput").value.split("\n").length},(_,i)=>i+1).join("\n");}
function message(text,ok){el("feedback").textContent=text;el("feedback").className=ok?"good":"bad";}
function render(){const p=problems[current];el("practice").hidden=false;el("completion").hidden=true;el("problemNumber").textContent=`문제 ${current+1}`;el("problemTitle").textContent=p.title;el("description").textContent=p.description;el("progressText").textContent=`${current+1} / ${problems.length}`;el("progressBar").style.width=`${(current+1)/problems.length*100}%`;el("conditionList").replaceChildren(...p.conditions.map(x=>{const li=document.createElement("li");li.textContent=x;return li;}));el("starterBox").hidden=!p.starter;el("starterCode").textContent=p.starter;el("expectedOutput").textContent=p.output;el("codeInput").value=p.starter;el("solutionPanel").hidden=true;el("solutionCode").textContent=p.solution;el("showSolution").textContent="정답 보기";el("teacherPrev").disabled=current===0;el("teacherNext").disabled=current===problems.length-1;message("",true);lines();}
function makeCompletionCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let value="V-";for(let i=0;i<4;i++)value+=chars[Math.floor(Math.random()*chars.length)];return value;}
function complete(){const now=new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date());el("practice").hidden=true;el("completion").hidden=false;el("progressText").textContent="8 / 8";el("progressBar").style.width="100%";el("completeStudent").textContent=studentNumber;el("completedAt").textContent=now;el("completionCode").textContent=makeCompletionCode();el("watermark").replaceChildren(...Array.from({length:20},()=>{const span=document.createElement("span");span.textContent=studentNumber;return span;}));scrollTo(0,0);}
function submit(){const code=el("codeInput").value;if(!code.trim())return message("코드를 작성한 후 확인하세요.",false);if(!problems[current].validate(code))return message("정답이 아닙니다. 조건과 변수 이름을 다시 확인하세요.",false);message("정답입니다! 다음 문제로 이동합니다.",true);el("submitButton").disabled=true;setTimeout(()=>{current++;el("submitButton").disabled=false;if(current===problems.length)complete();else render();},650);}
el("submitButton").addEventListener("click",submit);el("resetButton").addEventListener("click",()=>{el("codeInput").value=problems[current].starter;message("처음 상태로 되돌렸습니다.",true);lines();});el("restartButton").addEventListener("click",()=>location.reload());el("codeInput").addEventListener("input",lines);el("codeInput").addEventListener("scroll",()=>el("lineNumbers").scrollTop=el("codeInput").scrollTop);el("codeInput").addEventListener("keydown",e=>{if(e.key==="Tab"){e.preventDefault();const s=e.currentTarget.selectionStart;e.currentTarget.setRangeText("  ",s,e.currentTarget.selectionEnd,"end");lines();}if((e.ctrlKey||e.metaKey)&&e.key==="Enter")submit();});
window.addEventListener("message",event=>{if(event.origin!==location.origin||event.data?.type!=="session-context")return;studentNumber=event.data.studentNumber||"----";el("learnerText").textContent=`학번 ${studentNumber}`;el("teacherBar").hidden=!event.data.teacherMode;if(!event.data.teacherMode)el("solutionPanel").hidden=true;});
el("teacherPrev").addEventListener("click",()=>{if(current>0){current--;render();}});
el("teacherNext").addEventListener("click",()=>{if(current<problems.length-1){current++;render();}});
el("showSolution").addEventListener("click",()=>{const willShow=el("solutionPanel").hidden;el("solutionPanel").hidden=!willShow;el("showSolution").textContent=willShow?"정답 닫기":"정답 보기";});
el("copySolution").addEventListener("click",async()=>{await navigator.clipboard.writeText(problems[current].solution);el("copySolution").textContent="복사됨";setTimeout(()=>el("copySolution").textContent="복사",1200);});
render();
