const units={
arithmetic:{title:"산술 연산자",prefix:"OP-A",problems:[
{title:"전광판의 네 가지 계산",description:"제공 코드의 주석 부분을 알맞은 산술식으로 바꾸어 네 개의 결과를 차례대로 출력하세요.",conditions:["12와 5를 사용합니다.","첫 줄부터 +, -, *, / 연산자를 차례로 사용합니다.","계산 결과를 직접 적지 않습니다."],starter:"console.log(/* 덧셈식 */);\nconsole.log(/* 뺄셈식 */);\nconsole.log(/* 곱셈식 */);\nconsole.log(/* 나눗셈식 */);",output:"17\n7\n60\n2.4",solution:"console.log(12 + 5);\nconsole.log(12 - 5);\nconsole.log(12 * 5);\nconsole.log(12 / 5);",required:[/console\.log\(\s*12\s*\+\s*5\s*\)/,/console\.log\(\s*12\s*-\s*5\s*\)/,/console\.log\(\s*12\s*\*\s*5\s*\)/,/console\.log\(\s*12\s*\/\s*5\s*\)/]},
{title:"조각 케이크 나누기",description:"케이크 19조각을 4명이 똑같이 나눌 때 한 명이 받는 양을 계산하세요.",conditions:["total과 people 변수를 사용합니다.","/ 연산자를 사용합니다.","share 변수를 출력합니다."],starter:"const total = 19;\nconst people = 4;\nconst share = /* 계산식 */;\n\nconsole.log(share);",output:"4.75",solution:"const total = 19;\nconst people = 4;\nconst share = total / people;\n\nconsole.log(share);",required:[/const\s+share\s*=\s*total\s*\/\s*people/,/console\.log\(\s*share\s*\)/]},
{title:"포장 후 남은 배지",description:"배지 23개를 한 상자에 5개씩 포장한 뒤 남는 개수를 구하세요.",conditions:["badgeCount와 boxSize를 사용합니다.","% 연산자를 사용합니다.","remainder를 출력합니다."],starter:"const badgeCount = 23;\nconst boxSize = 5;\nconst remainder = /* 계산식 */;\n\nconsole.log(remainder);",output:"3",solution:"const badgeCount = 23;\nconst boxSize = 5;\nconst remainder = badgeCount % boxSize;\n\nconsole.log(remainder);",required:[/const\s+remainder\s*=\s*badgeCount\s*%\s*boxSize/,/console\.log\(\s*remainder\s*\)/]},
{title:"저장 공간 두 배 확장",description:"기본 용량 2가 8번 제곱된 값을 ** 연산자로 계산하세요.",conditions:["base와 count 변수를 사용합니다.","** 연산자를 사용합니다.","capacity를 출력합니다."],starter:"const base = 2;\nconst count = 8;\nconst capacity = /* 계산식 */;\n\nconsole.log(capacity);",output:"256",solution:"const base = 2;\nconst count = 8;\nconst capacity = base ** count;\n\nconsole.log(capacity);",required:[/const\s+capacity\s*=\s*base\s*\*\*\s*count/,/console\.log\(\s*capacity\s*\)/]},
{title:"오늘만 20% 할인",description:"56,000원인 상품을 20% 할인한 결제 금액을 계산하세요.",conditions:["price와 discount를 사용합니다.","할인 후 가격은 price * (1 - discount)로 계산합니다.","salePrice를 출력합니다."],starter:"const price = 56000;\nconst discount = 0.2;\nconst salePrice = /* 계산식 */;\n\nconsole.log(salePrice);",output:"44800",solution:"const price = 56000;\nconst discount = 0.2;\nconst salePrice = price * (1 - discount);\n\nconsole.log(salePrice);",required:[/const\s+salePrice\s*=\s*price\s*\*\s*\(\s*1\s*-\s*discount\s*\)/,/console\.log\(\s*salePrice\s*\)/]}
]},
assignment:{title:"대입 연산자",prefix:"OP-S",problems:[
{title:"다운로드 진행률 갱신",description:"30에서 시작한 진행률에 15를 더해 저장하세요.",conditions:["progress += 15를 사용합니다.","progress를 출력합니다."],starter:"let progress = 30;\n\n/* 복합 대입 연산자로 갱신 */\n\nconsole.log(progress);",output:"45",solution:"let progress = 30;\nprogress += 15;\n\nconsole.log(progress);",required:[/progress\s*\+=\s*15/,/console\.log\(\s*progress\s*\)/]},
{title:"배터리 사용량 반영",description:"100에서 시작한 배터리 잔량에서 사용량 35를 빼세요.",conditions:["battery -= 35를 사용합니다.","battery를 출력합니다."],starter:"let battery = 100;\n\n/* 복합 대입 연산자로 갱신 */\n\nconsole.log(battery);",output:"65",solution:"let battery = 100;\nbattery -= 35;\n\nconsole.log(battery);",required:[/battery\s*-=\s*35/,/console\.log\(\s*battery\s*\)/]},
{title:"포인트 변환 파이프라인",description:"포인트 12에 세 가지 복합 대입 연산을 순서대로 적용해 최종값을 만드세요.",conditions:["먼저 3을 곱합니다.","다음으로 2로 나눕니다.","마지막으로 5로 나눈 나머지를 저장합니다.","*=, /=, %=를 차례로 사용합니다."],starter:"let points = 12;\n\n/* 세 줄을 작성 */\n\nconsole.log(points);",output:"3",solution:"let points = 12;\npoints *= 3;\npoints /= 2;\npoints %= 5;\n\nconsole.log(points);",required:[/points\s*\*=\s*3[\s\S]*points\s*\/=\s*2[\s\S]*points\s*%=\s*5/,/console\.log\(\s*points\s*\)/]}
]},
comparison:{title:"비교 연산자",prefix:"OP-C",problems:[
{title:"탑승 가능 높이",description:"키가 140cm 이상인지 확인하는 비교식을 작성하세요.",conditions:["height와 minimumHeight를 사용합니다.",">= 연산자를 사용합니다."],starter:"const height = 140;\nconst minimumHeight = 140;\nconst canRide = /* 비교식 */;\n\nconsole.log(canRide);",output:"true",solution:"const height = 140;\nconst minimumHeight = 140;\nconst canRide = height >= minimumHeight;\n\nconsole.log(canRide);",required:[/canRide\s*=\s*height\s*>=\s*minimumHeight/,/console\.log\(\s*canRide\s*\)/]},
{title:"마감 시간을 넘겼을까",description:"현재 시간이 마감 시간보다 늦은지 확인하세요.",conditions:["currentHour와 deadline을 사용합니다.","> 연산자를 사용합니다."],starter:"const currentHour = 19;\nconst deadline = 18;\nconst isLate = /* 비교식 */;\n\nconsole.log(isLate);",output:"true",solution:"const currentHour = 19;\nconst deadline = 18;\nconst isLate = currentHour > deadline;\n\nconsole.log(isLate);",required:[/isLate\s*=\s*currentHour\s*>\s*deadline/,/console\.log\(\s*isLate\s*\)/]},
{title:"도로 결빙 주의",description:"현재 온도가 0보다 낮은지 확인하세요.",conditions:["temperature를 사용합니다.","< 연산자를 사용합니다."],starter:"const temperature = -2;\nconst isBelowZero = /* 비교식 */;\n\nconsole.log(isBelowZero);",output:"true",solution:"const temperature = -2;\nconst isBelowZero = temperature < 0;\n\nconsole.log(isBelowZero);",required:[/isBelowZero\s*=\s*temperature\s*<\s*0/,/console\.log\(\s*isBelowZero\s*\)/]},
{title:"초과와 이상의 경계",description:"점수 80이 기준 80을 초과하는지와 이상인지 차례로 확인하세요.",conditions:["첫 번째 비교에는 >를 사용합니다.","두 번째 비교에는 >=를 사용합니다."],starter:"const score = 80;\nconst standard = 80;\n\nconsole.log(/* 초과인지 확인 */);\nconsole.log(/* 이상인지 확인 */);",output:"false\ntrue",solution:"const score = 80;\nconst standard = 80;\n\nconsole.log(score > standard);\nconsole.log(score >= standard);",required:[/console\.log\(\s*score\s*>\s*standard\s*\)[\s\S]*console\.log\(\s*score\s*>=\s*standard\s*\)/]}
]},
equality:{title:"일치 연산자",prefix:"OP-E",problems:[
{title:"좌석 번호와 좌석 코드",description:"숫자 305와 문자열 305가 값과 자료형까지 같은지 확인하세요.",conditions:["=== 연산자를 사용합니다.","== 연산자는 사용하지 않습니다."],starter:'const seatNumber = 305;\nconst seatCode = "305";\n\nconsole.log(/* 일치 여부 */);',output:"false",solution:'const seatNumber = 305;\nconst seatCode = "305";\n\nconsole.log(seatNumber === seatCode);',required:[/console\.log\(\s*seatNumber\s*===\s*seatCode\s*\)/]},
{title:"관리자 계정이 아닌가",description:"현재 역할이 admin과 일치하지 않는지 확인하세요.",conditions:["!== 연산자를 사용합니다.","결과를 바로 출력합니다."],starter:'const role = "student";\n\nconsole.log(/* admin이 아닌지 확인 */);',output:"true",solution:'const role = "student";\n\nconsole.log(role !== "admin");',required:[/console\.log\(\s*role\s*!==\s*(["'])admin\1\s*\)/]},
{title:"배포 코드 검증",description:"배포 코드가 A17과 일치하는지, B17과 일치하지 않는지 차례로 확인하세요.",conditions:["첫 줄에는 ===를 사용합니다.","둘째 줄에는 !==를 사용합니다."],starter:'const deployCode = "A17";\n\nconsole.log(/* A17과 일치 */);\nconsole.log(/* B17과 불일치 */);',output:"true\ntrue",solution:'const deployCode = "A17";\n\nconsole.log(deployCode === "A17");\nconsole.log(deployCode !== "B17");',required:[/console\.log\(\s*deployCode\s*===\s*(["'])A17\1\s*\)[\s\S]*console\.log\(\s*deployCode\s*!==\s*(["'])B17\2\s*\)/]}
]},
logical:{title:"논리 연산자",prefix:"OP-L",problems:[
{title:"야간 전시 입장 조건",description:"나이가 18세 이상이고 입장권도 있어야 입장할 수 있습니다.",conditions:["두 비교 결과를 &&로 연결합니다.","canEnter를 출력합니다."],starter:"const age = 18;\nconst hasTicket = true;\nconst canEnter = /* 논리식 */;\n\nconsole.log(canEnter);",output:"true",solution:"const age = 18;\nconst hasTicket = true;\nconst canEnter = age >= 18 && hasTicket === true;\n\nconsole.log(canEnter);",required:[/canEnter\s*=\s*age\s*>=\s*18\s*&&\s*hasTicket\s*===\s*true/,/console\.log\(\s*canEnter\s*\)/]},
{title:"비상 연결망 선택",description:"와이파이 또는 모바일 데이터 중 하나라도 연결되어 있는지 확인하세요.",conditions:["wifi와 mobileData를 ||로 연결합니다."],starter:"const wifi = false;\nconst mobileData = true;\nconst isConnected = /* 논리식 */;\n\nconsole.log(isConnected);",output:"true",solution:"const wifi = false;\nconst mobileData = true;\nconst isConnected = wifi || mobileData;\n\nconsole.log(isConnected);",required:[/isConnected\s*=\s*wifi\s*\|\|\s*mobileData/,/console\.log\(\s*isConnected\s*\)/]},
{title:"잠기지 않은 문",description:"문이 잠겨 있지 않은 상태인지 ! 연산자로 확인하세요.",conditions:["isLocked 앞에 !를 사용합니다.","canOpen을 출력합니다."],starter:"const isLocked = false;\nconst canOpen = /* 논리식 */;\n\nconsole.log(canOpen);",output:"true",solution:"const isLocked = false;\nconst canOpen = !isLocked;\n\nconsole.log(canOpen);",required:[/canOpen\s*=\s*!\s*isLocked/,/console\.log\(\s*canOpen\s*\)/]},
{title:"모든 과목 통과 확인",description:"한 과목이라도 50점 미만이면 통과할 수 없습니다. 네 과목을 모두 확인하세요.",conditions:["각 점수를 50 이상인지 비교합니다.","네 비교식을 &&로 연결합니다."],starter:"const korean = 92;\nconst english = 47;\nconst math = 86;\nconst science = 81;\nconst passed = /* 논리식 */;\n\nconsole.log(passed);",output:"false",solution:"const korean = 92;\nconst english = 47;\nconst math = 86;\nconst science = 81;\nconst passed = korean >= 50 && english >= 50 && math >= 50 && science >= 50;\n\nconsole.log(passed);",required:[/passed\s*=\s*korean\s*>=\s*50\s*&&\s*english\s*>=\s*50\s*&&\s*math\s*>=\s*50\s*&&\s*science\s*>=\s*50/,/console\.log\(\s*passed\s*\)/]}
]},
increment:{title:"증감 연산자",prefix:"OP-I",problems:[
{title:"새 방문자 한 명",description:"현재 방문자 수에 한 명을 추가하세요.",conditions:["visitors++를 사용합니다.","visitors를 출력합니다."],starter:"let visitors = 9;\n\n/* 한 명 증가 */\n\nconsole.log(visitors);",output:"10",solution:"let visitors = 9;\nvisitors++;\n\nconsole.log(visitors);",required:[/visitors\s*\+\+/,/console\.log\(\s*visitors\s*\)/]},
{title:"재고 한 개 출고",description:"출고된 물건 한 개를 재고에서 차감하세요.",conditions:["stock--를 사용합니다.","stock을 출력합니다."],starter:"let stock = 4;\n\n/* 한 개 감소 */\n\nconsole.log(stock);",output:"3",solution:"let stock = 4;\nstock--;\n\nconsole.log(stock);",required:[/stock\s*--/,/console\.log\(\s*stock\s*\)/]},
{title:"먼저 출력할까, 먼저 증가할까",description:"후위 증가와 전위 증가를 사용하여 서로 다른 결과를 출력하세요.",conditions:["첫 출력문에는 a++를 사용합니다.","둘째 출력문에는 ++b를 사용합니다."],starter:"let a = 5;\nlet b = 5;\n\nconsole.log(/* 후위 증가 */);\nconsole.log(/* 전위 증가 */);",output:"5\n6",solution:"let a = 5;\nlet b = 5;\n\nconsole.log(a++);\nconsole.log(++b);",required:[/console\.log\(\s*a\+\+\s*\)[\s\S]*console\.log\(\s*\+\+b\s*\)/]}
]},
string:{title:"문자열 연산자",prefix:"OP-T",problems:[
{title:"띄어쓰기가 있는 이름표",description:"성을 나타내는 lastName과 이름을 나타내는 firstName 사이에 공백을 넣어 fullName을 만드세요.",conditions:["+ 연산자를 사용합니다.","공백 문자열을 사이에 넣습니다."],starter:'const lastName = "홍";\nconst firstName = "길동";\nconst fullName = /* 문자열 연결 */;\n\nconsole.log(fullName);',output:"홍 길동",solution:'const lastName = "홍";\nconst firstName = "길동";\nconst fullName = lastName + " " + firstName;\n\nconsole.log(fullName);',required:[/fullName\s*=\s*lastName\s*\+\s*(["'])\s\1\s*\+\s*firstName/,/console\.log\(\s*fullName\s*\)/]},
{title:"숫자가 들어간 회의실 표지",description:"문자열과 숫자를 +로 연결해 회의실 표지를 완성하세요.",conditions:["label과 roomNumber를 사용합니다.","result를 출력합니다."],starter:'const label = "회의실 ";\nconst roomNumber = 305;\nconst result = /* 문자열 연결 */;\n\nconsole.log(result);',output:"회의실 305",solution:'const label = "회의실 ";\nconst roomNumber = 305;\nconst result = label + roomNumber;\n\nconsole.log(result);',required:[/result\s*=\s*label\s*\+\s*roomNumber/,/console\.log\(\s*result\s*\)/]},
{title:"결합 순서가 만든 두 결과",description:"같은 값들을 서로 다른 순서로 연결하여 두 출력 결과를 만드세요.",conditions:["첫 줄은 10 + 20 + 점 순서로 작성합니다.","둘째 줄은 점수, 10, 20 순서로 작성합니다."],starter:'console.log(/* 30점 만들기 */);\nconsole.log(/* 점수: 1020 만들기 */);',output:"30점\n점수: 1020",solution:'console.log(10 + 20 + "점");\nconsole.log("점수: " + 10 + 20);',required:[/console\.log\(\s*10\s*\+\s*20\s*\+\s*(["'])점\1\s*\)[\s\S]*console\.log\(\s*(["'])점수:\s*\2\s*\+\s*10\s*\+\s*20\s*\)/]}
]},
ternary:{title:"삼항 연산자",prefix:"OP-3",problems:[
{title:"접속 상태 표시",description:"접속 여부에 따라 온라인 또는 오프라인을 선택하세요.",conditions:["삼항 연산자를 사용합니다.","isOnline이 true이면 온라인을 선택합니다."],starter:'const isOnline = true;\nconst status = /* 삼항 연산식 */;\n\nconsole.log(status);',output:"온라인",solution:'const isOnline = true;\nconst status = isOnline ? "온라인" : "오프라인";\n\nconsole.log(status);',required:[/status\s*=\s*isOnline\s*\?\s*(["'])온라인\1\s*:\s*(["'])오프라인\2/,/console\.log\(\s*status\s*\)/]},
{title:"재도전 여부 결정",description:"점수가 60 이상이면 통과, 그렇지 않으면 재도전을 저장하세요.",conditions:["score >= 60을 조건으로 사용합니다.","삼항 연산자의 결과를 result에 저장합니다."],starter:'const score = 67;\nconst result = /* 삼항 연산식 */;\n\nconsole.log(result);',output:"통과",solution:'const score = 67;\nconst result = score >= 60 ? "통과" : "재도전";\n\nconsole.log(result);',required:[/result\s*=\s*score\s*>=\s*60\s*\?\s*(["'])통과\1\s*:\s*(["'])재도전\2/,/console\.log\(\s*result\s*\)/]},
{title:"품절 표시 자동 선택",description:"재고가 있으면 판매 중, 없으면 품절을 표시하세요.",conditions:["stock > 0을 조건으로 사용합니다.","삼항 연산자를 한 번만 사용합니다."],starter:'const stock = 0;\nconst label = /* 삼항 연산식 */;\n\nconsole.log(label);',output:"품절",solution:'const stock = 0;\nconst label = stock > 0 ? "판매 중" : "품절";\n\nconsole.log(label);',required:[/label\s*=\s*stock\s*>\s*0\s*\?\s*(["'])판매 중\1\s*:\s*(["'])품절\2/,/console\.log\(\s*label\s*\)/]}
]},
precedence:{title:"연산자 우선순위",prefix:"OP-P",problems:[
{title:"곱셈이 먼저인 계산",description:"10, 20, 3을 사용하여 곱셈이 먼저 계산되고 결과가 70이 되는 식을 작성하세요.",conditions:["숫자는 각각 한 번씩 사용합니다.","괄호를 사용하지 않습니다.","결과를 result에 저장합니다."],starter:"const result = /* 계산식 */;\n\nconsole.log(result);",output:"70",solution:"const result = 10 + 20 * 3;\n\nconsole.log(result);",required:[/result\s*=\s*10\s*\+\s*20\s*\*\s*3/,/console\.log\(\s*result\s*\)/]},
{title:"덧셈을 먼저 만드는 괄호",description:"10, 20, 3을 사용하여 덧셈이 먼저 계산되고 결과가 90이 되는 식을 작성하세요.",conditions:["괄호 안에서 10 + 20을 먼저 계산합니다.","그 결과에 3을 곱합니다."],starter:"const result = /* 괄호가 있는 계산식 */;\n\nconsole.log(result);",output:"90",solution:"const result = (10 + 20) * 3;\n\nconsole.log(result);",required:[/result\s*=\s*\(\s*10\s*\+\s*20\s*\)\s*\*\s*3/,/console\.log\(\s*result\s*\)/]},
{title:"괄호만 추가해 true 만들기",description:"주어진 식에 괄호만 추가하여 결과가 true가 되게 하세요.",conditions:["숫자와 연산자는 변경하지 않습니다.","10 + 5가 먼저 계산되도록 괄호를 추가합니다."],starter:"const result = 10 + 5 * 2 > 25;\n\nconsole.log(result);",output:"true",solution:"const result = (10 + 5) * 2 > 25;\n\nconsole.log(result);",required:[/result\s*=\s*\(\s*10\s*\+\s*5\s*\)\s*\*\s*2\s*>\s*25/,/console\.log\(\s*result\s*\)/]},
{title:"논리 연산의 계산 순서",description:"같은 true와 false를 사용하되 두 번째 식에 괄호를 추가해 서로 다른 결과를 만드세요.",conditions:["첫 식에서는 &&가 ||보다 먼저 계산됩니다.","둘째 식에서는 true || false가 먼저 계산되게 합니다."],starter:"const result1 = /* 괄호 없는 논리식 */;\nconst result2 = /* 괄호가 있는 논리식 */;\n\nconsole.log(result1);\nconsole.log(result2);",output:"true\nfalse",solution:"const result1 = true || false && false;\nconst result2 = (true || false) && false;\n\nconsole.log(result1);\nconsole.log(result2);",required:[/result1\s*=\s*true\s*\|\|\s*false\s*&&\s*false/,/result2\s*=\s*\(\s*true\s*\|\|\s*false\s*\)\s*&&\s*false/,/console\.log\(\s*result1\s*\)[\s\S]*console\.log\(\s*result2\s*\)/]}
]}
};

const category=new URLSearchParams(location.search).get("category")||"arithmetic",unit=units[category]||units.arithmetic,problems=unit.problems;
let current=0,studentNumber="----";const el=id=>document.getElementById(id);const clean=code=>code.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\/\/.*$/gm,"");
function valid(code,p){const c=clean(code);return p.required.every(r=>r.test(c));}function lines(){el("lineNumbers").textContent=Array.from({length:el("codeInput").value.split("\n").length},(_,i)=>i+1).join("\n");}function message(t,ok){el("feedback").textContent=t;el("feedback").className=ok?"good":"bad";}
function render(){const p=problems[current];el("practice").hidden=false;el("completion").hidden=true;el("unitTitle").textContent=unit.title;el("problemNumber").textContent=`문제 ${current+1}`;el("problemTitle").textContent=p.title;el("description").textContent=p.description;el("progressText").textContent=`${current+1} / ${problems.length}`;el("progressBar").style.width=`${(current+1)/problems.length*100}%`;el("conditionList").replaceChildren(...p.conditions.map(x=>{const li=document.createElement("li");li.textContent=x;return li;}));el("starterCode").textContent=p.starter;el("expectedOutput").textContent=p.output;el("codeInput").value=p.starter;el("solutionPanel").hidden=true;el("solutionCode").textContent=p.solution;el("showSolution").textContent="정답 보기";el("teacherPrev").disabled=current===0;el("teacherNext").disabled=current===problems.length-1;message("",true);lines();}
function makeCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let code=unit.prefix+"-";for(let i=0;i<4;i++)code+=chars[Math.floor(Math.random()*chars.length)];return code;}function complete(){el("practice").hidden=true;el("completion").hidden=false;el("progressText").textContent=`${problems.length} / ${problems.length}`;el("progressBar").style.width="100%";el("completeTitle").textContent=`${unit.title} 완료`;el("completeStudent").textContent=studentNumber;el("completeCount").textContent=problems.length;el("completedAt").textContent=new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date());el("completionCode").textContent=makeCode();el("watermark").replaceChildren(...Array.from({length:20},()=>{const s=document.createElement("span");s.textContent=studentNumber;return s;}));scrollTo(0,0);}
function submit(){const code=el("codeInput").value;if(!code.trim())return message("코드를 작성한 후 확인하세요.",false);if(!valid(code,problems[current]))return message("정답이 아닙니다. 조건과 작성 위치를 다시 확인하세요.",false);message("정답입니다! 다음 문제로 이동합니다.",true);el("submitButton").disabled=true;setTimeout(()=>{current++;el("submitButton").disabled=false;current===problems.length?complete():render();},650);}
el("submitButton").addEventListener("click",submit);el("resetButton").addEventListener("click",()=>{el("codeInput").value=problems[current].starter;message("처음 상태로 되돌렸습니다.",true);lines();});el("restartButton").addEventListener("click",()=>location.reload());el("codeInput").addEventListener("input",lines);el("codeInput").addEventListener("scroll",()=>el("lineNumbers").scrollTop=el("codeInput").scrollTop);el("codeInput").addEventListener("keydown",e=>{if(e.key==="Tab"){e.preventDefault();const s=e.currentTarget.selectionStart;e.currentTarget.setRangeText("  ",s,e.currentTarget.selectionEnd,"end");lines();}if((e.ctrlKey||e.metaKey)&&e.key==="Enter")submit();});window.addEventListener("message",e=>{if(e.origin!==location.origin||e.data?.type!=="session-context")return;studentNumber=e.data.studentNumber||"----";el("learnerText").textContent=`학번 ${studentNumber}`;el("teacherBar").hidden=!e.data.teacherMode;if(!e.data.teacherMode)el("solutionPanel").hidden=true;});el("teacherPrev").addEventListener("click",()=>{if(current>0){current--;render();}});el("teacherNext").addEventListener("click",()=>{if(current<problems.length-1){current++;render();}});el("showSolution").addEventListener("click",()=>{const show=el("solutionPanel").hidden;el("solutionPanel").hidden=!show;el("showSolution").textContent=show?"정답 닫기":"정답 보기";});el("copySolution").addEventListener("click",async()=>{await navigator.clipboard.writeText(problems[current].solution);el("copySolution").textContent="복사됨";setTimeout(()=>el("copySolution").textContent="복사",1200);});render();
